nginx:
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always
dnsmasq:
  image: andyshinn/dnsmasq
  ports:
    - "192.168.99.100:53:53/tcp"
    - "192.168.99.100:53:53/udp"
  cap_add:
    - NET_ADMIN
  command: --address=/dev/192.168.99.100
  restart: always
mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ~/docker-volumes/mysql-data:/var/lib/mysql:rw
  ports:
    - "3306:3306"
